#!/bin/sh
#
# name     : tmuxauto， tmux environment make easy
# author   : shuoqi.yu shuoqi.yu@cs2c.com.cn
# license  : GPL
# created  : Dec 17 2019
# modified : Dec 20 2019
#

cmd=$(which tmux) # tmux path
session="Programing" # session name
work="cd ~/code/work/kylin-scanner/"
nfs="cd ~/nfs/"

if [ -z $cmd ]; then
  echo "You need to install tmux."
  exit 1
fi

# kill all tmux sessions
tmux kill-server

# session create, default window: 0:bash
$cmd new -s $session -d 

# window rename
tmux rename-window -t $session:0 "Journey"

# window create
# 1:Coding Directory
$cmd neww -a -n work -t $session  
$cmd send -t $session:work "$work" Enter

# 2:Compile: cd ~/rpmbuild/BUILD/
$cmd neww -a -n v7 -t $session
$cmd send -t $session:v7 "$nfs" Enter

# 3:Translation: trans :en
# $cmd neww -a -n Translation -t $session
# $cmd send -t $session:Translation "trans :en " Enter
# $cmd split-window -h -t $session:Translation 
# $cmd send -t $session:Translation "trans :zh " Enter

# window select 
$cmd selectw -t $session:1

# session attach
# $cmd attach -t $session
